dropdb: error: database removal failed: ERROR:  database "synthetic" does not exist
VACUUM
Importing file /data/Geographica2_Datasets/SyntheticWorkload/Synthetic/HEXAGON_LARGE.nt
log4j:ERROR Could not connect to remote log4j server at [localhost]. We will try again later.
0    [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Checking for locks...
388  [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Initialization completed.
391  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing file.
392  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] URL      : file:/data/Geographica2_Datasets/SyntheticWorkload/Synthetic/HEXAGON_LARGE.nt
392  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Context  : default
392  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Base URI : null
392  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Format   : N-Triples (mimeTypes=text/plain; ext=nt)
83155 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing was successful.
83155 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Closing connection...
83163 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Cleaning...
83170 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Clearing Successful.
83170 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Connection closed.
Importing file /data/Geographica2_Datasets/SyntheticWorkload/Synthetic/HEXAGON_LARGE_CENTER.nt
log4j:ERROR Could not connect to remote log4j server at [localhost]. We will try again later.
0    [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Checking for locks...
513  [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Initialization completed.
516  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing file.
517  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] URL      : file:/data/Geographica2_Datasets/SyntheticWorkload/Synthetic/HEXAGON_LARGE_CENTER.nt
517  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Context  : default
518  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Base URI : null
518  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Format   : N-Triples (mimeTypes=text/plain; ext=nt)
144885 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing was successful.
144885 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Closing connection...
144894 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Cleaning...
144900 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Clearing Successful.
144901 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Connection closed.
Importing file /data/Geographica2_Datasets/SyntheticWorkload/Synthetic/HEXAGON_SMALL.nt
log4j:ERROR Could not connect to remote log4j server at [localhost]. We will try again later.
0    [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Checking for locks...
699  [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Initialization completed.
702  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing file.
703  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] URL      : file:/data/Geographica2_Datasets/SyntheticWorkload/Synthetic/HEXAGON_SMALL.nt
703  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Context  : default
703  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Base URI : null
703  [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Format   : N-Triples (mimeTypes=text/plain; ext=nt)
1296290 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing was successful.
1296291 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Closing connection...
1296299 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Cleaning...
1296308 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Clearing Successful.
1296308 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Connection closed.
Importing file /data/Geographica2_Datasets/SyntheticWorkload/Synthetic/LINESTRING.nt
log4j:ERROR Could not connect to remote log4j server at [localhost]. We will try again later.
0    [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Checking for locks...
1885 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Initialization completed.
1888 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing file.
1890 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] URL      : file:/data/Geographica2_Datasets/SyntheticWorkload/Synthetic/LINESTRING.nt
1890 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Context  : default
1890 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Base URI : null
1890 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Format   : N-Triples (mimeTypes=text/plain; ext=nt)
6461 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing was successful.
6461 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Closing connection...
6470 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Cleaning...
6476 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Clearing Successful.
6476 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Connection closed.
Importing file /data/Geographica2_Datasets/SyntheticWorkload/Synthetic/POINT.nt
log4j:ERROR Could not connect to remote log4j server at [localhost]. We will try again later.
0    [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Checking for locks...
1828 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Initialization completed.
1830 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing file.
1832 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] URL      : file:/data/Geographica2_Datasets/SyntheticWorkload/Synthetic/POINT.nt
1832 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Context  : default
1832 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Base URI : null
1833 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Format   : N-Triples (mimeTypes=text/plain; ext=nt)
979555 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.storeURL] Storing was successful.
979556 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Closing connection...
979565 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Cleaning...
979573 [main] INFO  eu.earthobservatory.runtime.postgis.Strabon  - [Strabon] Clearing Successful.
979573 [main] INFO  eu.earthobservatory.runtime.generaldb.Strabon  - [Strabon.close] Connection closed.
